- name: Install mongodb
  hosts: mongodb
  become: yes

  tasks:
  - name: Copy maongodb repo file
    ansible.builtin.copy: 
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb server
    ansible.builtin.dnf:
      name: mongodb-org
      state: present

  - name: Start mongodb service
    ansible.builtin.systemd:
      name: mongod
      state: started
      enabled: true

  - name: Allow remote connection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Restart mongodb service
    ansible.builtin.systemd:
      name: mongod
      state: restarted